<![CDATA[// ============================================================
// thingProperties.example.h — Arduino IoT Cloud Configuration
// ============================================================
// INSTRUCTIONS:
//   1. Copy this file to: src/nodemcu_master/thingProperties.h
//   2. Replace the placeholder values with your actual cloud config
//   3. NEVER commit thingProperties.h to version control
//
// NOTE: This file is auto-generated by Arduino IoT Cloud.
//       If you're using Sinric Pro instead, you may not need this.
// ============================================================

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "your-device-uuid-here";

const char SSID[]               = "YourWiFiNetworkName";
const char PASS[]               = "YourWiFiPassword";
const char DEVICE_KEY[]         = "YourDeviceKeyHere";

CloudRelativeHumidity humidity_Sensor;

void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity_Sensor, READ, 60 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
]]>
